### ISSUE TITLE
Suggestion on naming declaration.

### ISSUE THREAD

**Issue by 13014932** [akhilraw/ctetform#2]
@akhilraw recheck your naming declaration on db structure.

-  id column may always in numbers. so use the only id here not `id_number`.
-  column name should be easily readable by others. not like given `statusof_q_exm`  `q_paper_medium`. here you can use column `status` , `medium`. 
-  `pass_word`  there is not must. That you have to use underscore between column names.

**Comment by akhilraw** [comment]
there were two id columns i.e(id type and id number) 
password is i think a keyword in cause its color was different when i used password name

anyways thankyou for your suggestion & guidance i'll keep that in mind while creating future tables
